#!/usr/bin/env python3
"""Print an OS-level sandbox starting point from the same config the hook uses.

    gen_sandbox.py bwrap | seatbelt | windows | all

This tool only PRINTS text. It never runs bwrap, sandbox-exec or icacls, and
every path is quoted for the target syntax, so a hostile path in the config
cannot execute anything here.

Why it exists: the hook reads command text, and command text cannot bound what
a shell or interpreter does. An OS-level layer is what actually enforces a
boundary, so one config should drive both.
"""
import glob
import os
import re
import shlex
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(HERE), "hooks"))

import guardrail_config as gconfig  # noqa: E402
import guardrail_defaults as defaults  # noqa: E402

DISCLAIMER = ("Generated by agent-guardrail gen_sandbox.py: a starting point, "
              "not tested on your system; review before use.")
TARGETS = ("bwrap", "seatbelt", "windows")
PLATFORM_FOR = {"bwrap": "linux", "seatbelt": "darwin", "windows": "win32"}
# bwrap supplies fresh /dev and /proc itself; re-binding them would conflict.
BWRAP_SKIP = ("/dev", "/proc")
# A newline in a path would start a new line in the printed script.
_CONTROL = re.compile(r"[\x00-\x1f\x7f]")


def collect(target):
    """Return [(path, reason, [writable exceptions])] for one target."""
    cfg = gconfig.load_config()
    home = gconfig.home_dir()
    entries = []
    for item in cfg["protected_paths"]:
        entries.append((os.path.expanduser(item["path"]), item["reason"], []))
    if cfg["builtin_os_protection"]:
        for e in defaults.os_entries(PLATFORM_FOR[target], home, os.environ):
            entries.append((e["path"], e["reason"], e["except"]))
    # The guard protects itself from the agent here too, at the OS layer.
    if cfg["found"]:
        entries.append((cfg["path"], "guard config", []))
    entries.append((gconfig.state_dir(), "guard approval state", []))
    entries.append((gconfig.HOOKS_DIR, "guard hook scripts", []))
    for name in ("settings.json", "settings.local.json"):
        entries.append((os.path.join(home, ".claude", name),
                        "Claude Code settings (hook registration)", []))
    for path, _, exc in entries:
        for p in [path] + list(exc):
            if _CONTROL.search(p):
                raise gconfig.ConfigError("path contains a control character: %r" % p)
    seen, unique = set(), []
    for path, reason, exc in entries:
        if path not in seen:
            seen.add(path)
            unique.append((path, reason, exc))
    return unique


def gen_bwrap():
    lines = [
        "# " + DISCLAIMER,
        "# Usage: save as agent-sandbox.sh, chmod +x, then ./agent-sandbox.sh claude",
        "# The whole filesystem stays writable except the paths below, which are",
        "# mounted read-only on top. Reads are NOT restricted: add --tmpfs <dir> to hide one.",
        "# On Ubuntu 24.04+ unprivileged user namespaces are restricted by AppArmor, which",
        "# can make bwrap fail; a scoped AppArmor profile that allows 'userns' for bwrap fixes it.",
        "# Mount order (later mounts overlay earlier ones) follows the bwrap manual but is",
        "# unverified on your kernel. Also read-only here: Claude Code settings, so changing",
        "# them requires a shell outside this sandbox.",
        "exec bwrap \\",
        "  --bind / / \\",
        "  --dev /dev \\",
        "  --proc /proc \\",
    ]
    for path, reason, exceptions in collect("bwrap"):
        if path in BWRAP_SKIP or path.startswith(tuple(p + "/" for p in BWRAP_SKIP)):
            continue
        # Globs such as /lib* expand now, because bwrap does not expand them.
        targets = sorted(glob.glob(path)) if any(c in path for c in "*?[") else [path]
        for t in targets or [path]:
            q = shlex.quote(t)
            # No trailing comment: anything after a line-continuation backslash
            # would break the command.
            lines.append("  --ro-bind-try %s %s \\" % (q, q))
            for exc in exceptions:
                qe = shlex.quote(exc)
                lines.append("  --bind-try %s %s \\" % (qe, qe))
    lines.append('  -- "$@"')
    return "\n".join(lines) + "\n"


def _sbpl(path):
    return '"%s"' % path.replace("\\", "\\\\").replace('"', '\\"')


def gen_seatbelt():
    lines = [
        "; " + DISCLAIMER,
        "; Usage: sandbox-exec -f agent.sb claude",
        "; sandbox-exec is deprecated by Apple but still functional.",
        "; Rules are evaluated so that a later matching rule wins; the (allow ...) lines",
        "; for writable exceptions rely on that and are unverified on your macOS version.",
        "(version 1)",
        "(allow default)",
    ]
    entries = collect("seatbelt")
    for path, reason, _ in entries:
        kind = "literal" if os.path.isfile(path) else "subpath"
        lines.append("(deny file-write* (%s %s)) ; %s" % (kind, _sbpl(path), reason))
    for path, _, exceptions in entries:
        for exc in exceptions:
            lines.append("(allow file-write* (subpath %s)) ; exception inside %s" % (_sbpl(exc), path))
    return "\n".join(lines) + "\n"


def _cmd(path):
    # In a .bat file % starts a variable and " ends a quoted string.
    return '"%s"' % path.replace("%", "%%").replace('"', "")


def gen_windows():
    lines = [
        "REM " + DISCLAIMER,
        "REM Native Windows has no equivalent of bwrap or Seatbelt in this project.",
        "REM Claude Code's built-in sandbox is not supported on native Windows, so the options are:",
        "REM  1. WSL2 (recommended): run the agent inside a WSL2 distribution. Windows files are",
        "REM     reachable only through /mnt/c, and the output of 'gen_sandbox.py bwrap' applies there.",
        "REM  2. A dedicated low-privilege Windows account for the agent, plus the deny ACEs below.",
        "REM WARNING: a deny ACE on your own account also blocks YOU. Replace %USERNAME% with the",
        "REM dedicated agent account before running anything.",
        "REM Review each line first; icacls /deny changes permissions on real paths.",
    ]
    for path, reason, _ in collect("windows"):
        flags = "(OI)(CI)(W,D,DC)" if not os.path.isfile(path) else "(W,D,DC)"
        lines.append("REM %s" % reason.replace("\n", " "))
        lines.append("icacls %s /deny %%AGENT_USER%%:%s" % (_cmd(path), flags))
    return "\n".join(lines) + "\n"


GENERATORS = {"bwrap": gen_bwrap, "seatbelt": gen_seatbelt, "windows": gen_windows}


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if len(argv) != 1 or argv[0] not in TARGETS + ("all",):
        sys.stderr.write("usage: gen_sandbox.py bwrap | seatbelt | windows | all\n")
        return 2
    try:
        names = TARGETS if argv[0] == "all" else (argv[0],)
        sys.stdout.write("\n".join(GENERATORS[n]() for n in names))
    except gconfig.ConfigError as exc:
        sys.stderr.write("gen_sandbox: %s\n" % exc)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
